import { GoogleGenAI } from "@google/genai";

export interface GenerationOptions {
  aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9";
  imageSize: "1K" | "2K" | "4K";
  backgroundColor: string;
  isTransparent: boolean;
  customPrompt: string;
  lightDirection: string;
  showShadow: boolean;
}

export async function transformProductImage(
  base64Image: string,
  mimeType: string,
  options: GenerationOptions
) {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  const backgroundDesc = options.isTransparent 
    ? "on a transparent background (PNG style)" 
    : `on a clean, solid ${options.backgroundColor} background`;

  const lightShadowMap: Record<string, string> = {
    "top-left": "Light coming from the top-left",
    "top-right": "Light coming from the top-right",
    "top": "Light coming from directly above",
    "left": "Light coming from the left side",
    "right": "Light coming from the right side",
    "front": "Light coming from the front"
  };

  const lightDesc = lightShadowMap[options.lightDirection] || lightShadowMap["top-left"];
  
  const shadowPrompt = options.showShadow 
    ? `Add a "Premium European Cookware Studio Shadow":
       - DIFFUSED SPREAD: Create a soft, wide, natural diffused shadow that spreads slightly wider around the product base, similar to high-end European cookware brands.
       - OCCLUSION GRADIENT: The shadow should be darker near the base (subtle occlusion) and fade smoothly outward with very soft, feathered edges.
       - COLOR & TONE: Maintain a light grey tone for the shadow, avoiding pure black.
       - FIDELITY: Ensure the shadow is realistic and physically accurate based on the light source (${options.lightDirection}).
       - FORBID: No dramatic or hard shadows. Do not darken the overall background. Maintain a clean premium white studio aesthetic.`
    : "DO NOT add any cast shadows. The product should appear as if it's floating or in a shadowless environment, but still maintain its internal shading and reflections.";

  const prompt = `
    TASK: Perform a professional studio lighting and retouch adjustment on this product photo. This is NOT a redesign; the product must remain physically identical to the source.
    
    STYLE REFERENCE: Caraway Home, Our Place, minimalist aesthetic.
    
    KEY REQUIREMENTS:
    - RETOUCH ONLY: This edit must function as a lighting and retouch adjustment only. Do NOT redesign, regenerate, or alter the product's physical structure.
    - PERSPECTIVE & GEOMETRY LOCK: Preserve original product geometry, proportions, and perspective exactly as in the input image. Do NOT change camera angle, lens distortion, or product structure. No reshaping, no redesign, no symmetry correction.
    - MATERIAL & COLOR FIDELITY: Maintain accurate material properties, original colors, and surface curvature. Do NOT change the product's color or material.
    - STUDIO RETOUCH: Clean background to ${backgroundDesc}, remove distractions, and enhance clarity.
    - LIGHTING: ${lightDesc}. Use high-end, physically accurate studio lighting with bright midtones.
    - SHADOWS: ${shadowPrompt}
    - Quality: Ultra-sharp, high contrast, professional color grading.
    - Additional User Instructions: ${options.customPrompt || "None"}
    
    OUTPUT: A single high-quality image of the product in this new studio setting.
  `.trim();

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image.split(',')[1],
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: options.aspectRatio,
        imageSize: options.imageSize,
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}
