import { GoogleGenAI } from "@google/genai";

export interface GenerationOptions {
  aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9";
  imageSize: "1K" | "2K" | "4K";
  backgroundColor: string;
  isTransparent: boolean;
  customPrompt: string;
  lightDirection: string;
  showShadow: boolean;
  surfaceType: string;
  horizonStyle: string;
  stylePreset: string;
  backgroundImage?: string;
  backgroundImageMimeType?: string;
}

export async function transformProductImage(
  base64Images: string | string[],
  mimeType: string | string[],
  options: GenerationOptions
) {
  const ai = new GoogleGenAI({ 
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
  
  const images = Array.isArray(base64Images) ? base64Images : [base64Images];
  const mimeTypes = Array.isArray(mimeType) ? mimeType : [mimeType];

  const isMulti = images.length > 1;
  const styleInstruction = options.stylePreset === 'caraway' 
    ? "Style: Caraway (airy, minimal, pastel, editorial, premium US/EU look)"
    : options.stylePreset === 'our-place'
    ? "Style: Our Place (warm, lifestyle, soft emotional realism)"
    : "Style: Neutral Premium (clean modern studio-commercial look)";

  const prompt = `
[AUTO MODE SMART DETECTION]
Analyze the uploaded background and product images to choose the correct workflow.

1. BACKGROUND TYPE DETECTION:
- If background is pure white, near-white studio, or transparent: Use [WHITE BACKGROUND MODE].
- If background contains walls, floors, shelves, tables, perspective lines, or environmental depth: Use [SCENE BACKGROUND MODE].

2. PLACEMENT INTENT DETECTION:
- If background has a visible hero object in a clear placement zone: Use [REPLACE EXISTING PRODUCT MODE].
  - Cleanly remove the existing object without damaging the environment.
  - Insert new product(s) into the exact same placement zone.
- If background has empty surface area and no obvious hero object: Use [ADD NEW PRODUCT MODE].
  - Detect best valid placement surface and place product(s) physically believably.

3. MULTI-PRODUCT LOGIC:
${isMulti ? `
- You are processing multiple product images.
- Detect if they form a coordinated set or are variants.
- Arrange them naturally with consistent spacing and realistic scale relationships.
- Align all products to the same perspective and lighting direction.
- Generate separate, realistic contact shadows for each item.
` : "- You are processing a single product image."}

4. LIGHTING & PERSPECTIVE AUTO MATCH:
- Detect main light direction, hardness, and ambient fill from the scene.
- Match camera height, viewing angle, and horizon level.
- Force inserted product(s) to match background perspective (no top-view in eye-level scenes, etc.).
- Apply correct contact shadows and environmental lighting.

5. PRODUCT INTEGRITY (STRICT RULE):
- PRESERVE EXACT PRODUCT SHAPE, COLOR, MATERIAL, LOGO, AND DETAILS.
- NO REDESIGN, NO RESTYLING, NO AI REINTERPRETATION.
- Only allowed changes: scale, position, perspective fitting, lighting integration, shadow generation.

6. STYLE & QUALITY:
- ${styleInstruction}
- Output: ${options.imageSize} Ultra Sharp, realistic commercial advertising quality.
- Clean edges, realistic grounding, no fake compositing look.

${options.customPrompt ? `Additional User Request: ${options.customPrompt}` : ""}

[FIX MODE]
If generation result shows wrong perspective, floating objects, or color shifts, automatically trigger correction priority to restore product integrity and fix placement.
`.trim();

  const parts: any[] = images.map((img, idx) => ({
    inlineData: {
      data: img.split(',')[1],
      mimeType: Array.isArray(mimeTypes) ? mimeTypes[idx] : mimeTypes,
    },
  }));

  if (options.backgroundImage && options.backgroundImageMimeType) {
    parts.push({
      inlineData: {
        data: options.backgroundImage.split(',')[1],
        mimeType: options.backgroundImageMimeType,
      },
    });
  }

  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image',
    contents: {
      parts: parts,
    },
    config: {
      imageConfig: {
        aspectRatio: options.aspectRatio,
        imageSize: options.imageSize,
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}
